module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/ENTER_URL👈?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/j7mio9.png',
    NEWSLETTER_JID: '120363419333086422@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᴍᴜʟʟᴇʀ ᴍɪɴɪ ʙᴏᴛ ',
    OWNER_NAME: 'MULLER TECH',
    OWNER_NUMBER: '2349166255902',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴍᴜʟʟᴇʀ  ᴛᴇᴄʜ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBiO8PEKyZ9i8Skkc3C',
};
